#Requires -Version 7.0

<#
.SYNOPSIS
Creates the Azure DevOps Workload Identity Federation Service Connections
for Application Landing Zone Terraform.

.DESCRIPTION
Creates:

  sc-app-lz-plan
      -> uami-tf-app-plan

  sc-app-lz-apply
      -> uami-tf-app-apply

The script:
  1. Uses a short-lived Azure DevOps PAT via AZURE_DEVOPS_EXT_PAT.
  2. Looks up the existing user-assigned managed identities.
  3. Creates Azure DevOps ARM Service Connections using
     WorkloadIdentityFederation.
  4. Reads the WIF issuer and subject generated by Azure DevOps.
  5. Creates the corresponding federated identity credential
     on each managed identity.
  6. Is safe to re-run.

PREREQUISITES
--------------
- Azure CLI installed.
- Azure DevOps CLI extension available.
- Logged into Azure using `az login`.
- Environment variable AZURE_DEVOPS_EXT_PAT set to a short-lived PAT.
- The two managed identities must already exist.

Example:

$env:AZURE_DEVOPS_EXT_PAT = "<PAT>"

.\New-ApplicationServiceConnections.ps1 `
    -AzureDevOpsOrganizationUrl "https://dev.azure.com/ACME" `
    -AzureDevOpsProjectName "ACME_ADO_PROJECT" `
    -ManagementSubscriptionId "<management-subscription-guid>" `
    -ManagedIdentityResourceGroupName "rg-app-tf-bootstrap-uks-001-identity" `
    -PlanManagedIdentityName "uami-tf-app-plan" `
    -ApplyManagedIdentityName "uami-tf-app-apply"
#>

[CmdletBinding()]
param (
    [Parameter(Mandatory)]
    [string]$AzureDevOpsOrganizationUrl,

    [Parameter(Mandatory)]
    [string]$AzureDevOpsProjectName,

    [Parameter(Mandatory)]
    [string]$ManagementSubscriptionId,

    [Parameter(Mandatory)]
    [string]$ManagedIdentityResourceGroupName,

    [Parameter()]
    [string]$PlanManagedIdentityName = "uami-tf-app-plan",

    [Parameter()]
    [string]$ApplyManagedIdentityName = "uami-tf-app-apply",

    [Parameter()]
    [string]$PlanServiceConnectionName = "sc-app-lz-plan",

    [Parameter()]
    [string]$ApplyServiceConnectionName = "sc-app-lz-apply",

    [Parameter()]
    [string]$PlanFederatedCredentialName = "fic-ado-app-lz-plan",

    [Parameter()]
    [string]$ApplyFederatedCredentialName = "fic-ado-app-lz-apply"
)

$ErrorActionPreference = "Stop"

# ------------------------------------------------------------
# Helper functions
# ------------------------------------------------------------

function Assert-LastExitCode {
    param(
        [string]$Action
    )

    if ($LASTEXITCODE -ne 0) {
        throw "$Action failed. Azure CLI exit code: $LASTEXITCODE"
    }
}

function Invoke-AzJson {
    param(
        [Parameter(Mandatory)]
        [string[]]$Arguments
    )

    $result = & az @Arguments
    Assert-LastExitCode -Action "Azure CLI command: az $($Arguments -join ' ')"

    if ([string]::IsNullOrWhiteSpace(($result -join "`n"))) {
        return $null
    }

    return (($result -join "`n") | ConvertFrom-Json)
}

function Get-ServiceConnection {
    param(
        [Parameter(Mandatory)]
        [string]$Name
    )

    $connections = Invoke-AzJson -Arguments @(
        "devops", "service-endpoint", "list",
        "--organization", $AzureDevOpsOrganizationUrl,
        "--project", $AzureDevOpsProjectName,
        "--output", "json"
    )

    return $connections |
        Where-Object { $_.name -eq $Name } |
        Select-Object -First 1
}

function Get-ServiceConnectionDetail {
    param(
        [Parameter(Mandatory)]
        [string]$Id
    )

    return Invoke-AzJson -Arguments @(
        "devops", "service-endpoint", "show",
        "--id", $Id,
        "--organization", $AzureDevOpsOrganizationUrl,
        "--project", $AzureDevOpsProjectName,
        "--output", "json"
    )
}

function New-OrGetServiceConnection {
    param(
        [Parameter(Mandatory)]
        [string]$ServiceConnectionName,

        [Parameter(Mandatory)]
        [string]$ManagedIdentityClientId,

        [Parameter(Mandatory)]
        [string]$TenantId,

        [Parameter(Mandatory)]
        [string]$SubscriptionId,

        [Parameter(Mandatory)]
        [string]$SubscriptionName,

        [Parameter(Mandatory)]
        [string]$ProjectId
    )

    $existing = Get-ServiceConnection -Name $ServiceConnectionName

    if ($existing) {
        Write-Host "Service Connection '$ServiceConnectionName' already exists."
        return Get-ServiceConnectionDetail -Id $existing.id
    }

    Write-Host "Creating Service Connection '$ServiceConnectionName'..."

    $configuration = @{
        data = @{
            subscriptionId   = $SubscriptionId
            subscriptionName = $SubscriptionName
            environment      = "AzureCloud"
            scopeLevel       = "Subscription"
            creationMode     = "Manual"
        }

        name = $ServiceConnectionName

        type = "AzureRM"

        url = "https://management.azure.com/"

        authorization = @{
            parameters = @{
                tenantid           = $TenantId
                serviceprincipalid = $ManagedIdentityClientId
            }

            scheme = "WorkloadIdentityFederation"
        }

        isShared = $false

        isReady = $true

        serviceEndpointProjectReferences = @(
            @{
                projectReference = @{
                    id   = $ProjectId
                    name = $AzureDevOpsProjectName
                }

                name = $ServiceConnectionName
            }
        )
    }

    $json = $configuration | ConvertTo-Json -Depth 20

    $tempFile = Join-Path `
        -Path ([System.IO.Path]::GetTempPath()) `
        -ChildPath "$([Guid]::NewGuid()).json"

    try {
        # Write UTF-8 without BOM
        [System.IO.File]::WriteAllText(
            $tempFile,
            $json,
            [System.Text.UTF8Encoding]::new($false)
        )

        $created = Invoke-AzJson -Arguments @(
            "devops", "service-endpoint", "create",
            "--service-endpoint-configuration", $tempFile,
            "--organization", $AzureDevOpsOrganizationUrl,
            "--project", $AzureDevOpsProjectName,
            "--output", "json"
        )

        Write-Host "Created Service Connection '$ServiceConnectionName'."

        return Get-ServiceConnectionDetail -Id $created.id
    }
    finally {
        if (Test-Path $tempFile) {
            Remove-Item $tempFile -Force
        }
    }
}

function New-OrValidateFederatedCredential {
    param(
        [Parameter(Mandatory)]
        [string]$ManagedIdentityName,

        [Parameter(Mandatory)]
        [string]$FederatedCredentialName,

        [Parameter(Mandatory)]
        [string]$Issuer,

        [Parameter(Mandatory)]
        [string]$Subject
    )

    $existingCredentials = Invoke-AzJson -Arguments @(
        "identity", "federated-credential", "list",
        "--identity-name", $ManagedIdentityName,
        "--resource-group", $ManagedIdentityResourceGroupName,
        "--subscription", $ManagementSubscriptionId,
        "--output", "json"
    )

    $existing = $existingCredentials |
        Where-Object { $_.name -eq $FederatedCredentialName } |
        Select-Object -First 1

    if ($existing) {
        Write-Host "Federated credential '$FederatedCredentialName' already exists."

        if ($existing.issuer -ne $Issuer) {
            throw @"
Federated credential '$FederatedCredentialName' exists but the issuer differs.

Existing:
$($existing.issuer)

Expected:
$Issuer

The script will not modify this automatically.
"@
        }

        if ($existing.subject -ne $Subject) {
            throw @"
Federated credential '$FederatedCredentialName' exists but the subject differs.

Existing:
$($existing.subject)

Expected:
$Subject

The script will not modify this automatically.
"@
        }

        Write-Host "Federated credential configuration is correct."
        return
    }

    Write-Host "Creating federated credential '$FederatedCredentialName'..."

    & az identity federated-credential create `
        --name $FederatedCredentialName `
        --identity-name $ManagedIdentityName `
        --resource-group $ManagedIdentityResourceGroupName `
        --subscription $ManagementSubscriptionId `
        --issuer $Issuer `
        --subject $Subject `
        --audiences "api://AzureADTokenExchange" `
        --output none

    Assert-LastExitCode `
        -Action "Create federated identity credential '$FederatedCredentialName'"

    Write-Host "Created federated credential '$FederatedCredentialName'."
}

function Configure-ServiceConnection {
    param(
        [Parameter(Mandatory)]
        [string]$ManagedIdentityName,

        [Parameter(Mandatory)]
        [string]$ServiceConnectionName,

        [Parameter(Mandatory)]
        [string]$FederatedCredentialName,

        [Parameter(Mandatory)]
        [string]$TenantId,

        [Parameter(Mandatory)]
        [string]$SubscriptionId,

        [Parameter(Mandatory)]
        [string]$SubscriptionName,

        [Parameter(Mandatory)]
        [string]$ProjectId
    )

    Write-Host ""
    Write-Host "------------------------------------------------------------"
    Write-Host "Configuring $ServiceConnectionName"
    Write-Host "------------------------------------------------------------"

    $identity = Invoke-AzJson -Arguments @(
        "identity", "show",
        "--name", $ManagedIdentityName,
        "--resource-group", $ManagedIdentityResourceGroupName,
        "--subscription", $ManagementSubscriptionId,
        "--output", "json"
    )

    if (-not $identity) {
        throw "Managed Identity '$ManagedIdentityName' was not found."
    }

    Write-Host "Managed Identity : $ManagedIdentityName"
    Write-Host "Client ID        : $($identity.clientId)"
    Write-Host "Principal ID     : $($identity.principalId)"

    $serviceConnection = New-OrGetServiceConnection `
        -ServiceConnectionName $ServiceConnectionName `
        -ManagedIdentityClientId $identity.clientId `
        -TenantId $TenantId `
        -SubscriptionId $SubscriptionId `
        -SubscriptionName $SubscriptionName `
        -ProjectId $ProjectId

    $serviceConnection = Get-ServiceConnectionDetail `
        -Id $serviceConnection.id

    $issuer =
        $serviceConnection.authorization.parameters.workloadIdentityFederationIssuer

    $subject =
        $serviceConnection.authorization.parameters.workloadIdentityFederationSubject

    if ([string]::IsNullOrWhiteSpace($issuer)) {
        throw "Azure DevOps did not return a workload identity federation issuer for '$ServiceConnectionName'."
    }

    if ([string]::IsNullOrWhiteSpace($subject)) {
        throw "Azure DevOps did not return a workload identity federation subject for '$ServiceConnectionName'."
    }

    Write-Host "WIF Issuer  : $issuer"
    Write-Host "WIF Subject : $subject"

    New-OrValidateFederatedCredential `
        -ManagedIdentityName $ManagedIdentityName `
        -FederatedCredentialName $FederatedCredentialName `
        -Issuer $issuer `
        -Subject $subject

    Write-Host ""
    Write-Host "'$ServiceConnectionName' configuration complete."

    return [PSCustomObject]@{
        ServiceConnectionName = $ServiceConnectionName
        ServiceConnectionId   = $serviceConnection.id
        ManagedIdentityName   = $ManagedIdentityName
        ClientId              = $identity.clientId
        PrincipalId           = $identity.principalId
        Issuer                = $issuer
        Subject               = $subject
    }
}

# ------------------------------------------------------------
# Prerequisite validation
# ------------------------------------------------------------

Write-Host ""
Write-Host "Application Terraform Service Connection Bootstrap"
Write-Host "=================================================="

if ([string]::IsNullOrWhiteSpace($env:AZURE_DEVOPS_EXT_PAT)) {
    throw @"
AZURE_DEVOPS_EXT_PAT is not set.

Create a short-lived Azure DevOps PAT with the minimum permissions
necessary to manage Service Connections, then set it in this
PowerShell session:

`$env:AZURE_DEVOPS_EXT_PAT = "<PAT>"

Do not store the PAT in the script or commit it to source control.
"@
}

# Check Azure CLI
& az version --output none

if ($LASTEXITCODE -ne 0) {
    throw "Azure CLI is not installed or cannot be executed."
}

# Install Azure DevOps extension if missing.
$extensions = Invoke-AzJson -Arguments @(
    "extension", "list",
    "--output", "json"
)

$devopsExtension =
    $extensions | Where-Object { $_.name -eq "azure-devops" }

if (-not $devopsExtension) {
    Write-Host "Installing Azure DevOps CLI extension..."

    & az extension add --name azure-devops --output none

    Assert-LastExitCode `
        -Action "Install Azure DevOps CLI extension"
}

# ------------------------------------------------------------
# Azure subscription / tenant details
# ------------------------------------------------------------

$subscription = Invoke-AzJson -Arguments @(
    "account", "show",
    "--subscription", $ManagementSubscriptionId,
    "--output", "json"
)

$tenantId         = $subscription.tenantId
$subscriptionName = $subscription.name

Write-Host ""
Write-Host "Azure:"
Write-Host "  Subscription : $subscriptionName"
Write-Host "  ID           : $ManagementSubscriptionId"
Write-Host "  Tenant       : $tenantId"

# ------------------------------------------------------------
# Azure DevOps project details
# ------------------------------------------------------------

$project = Invoke-AzJson -Arguments @(
    "devops", "project", "show",
    "--organization", $AzureDevOpsOrganizationUrl,
    "--project", $AzureDevOpsProjectName,
    "--output", "json"
)

$projectId = $project.id

Write-Host ""
Write-Host "Azure DevOps:"
Write-Host "  Organisation : $AzureDevOpsOrganizationUrl"
Write-Host "  Project      : $AzureDevOpsProjectName"
Write-Host "  Project ID   : $projectId"

# ------------------------------------------------------------
# Plan Service Connection
# ------------------------------------------------------------

$planResult = Configure-ServiceConnection `
    -ManagedIdentityName $PlanManagedIdentityName `
    -ServiceConnectionName $PlanServiceConnectionName `
    -FederatedCredentialName $PlanFederatedCredentialName `
    -TenantId $tenantId `
    -SubscriptionId $ManagementSubscriptionId `
    -SubscriptionName $subscriptionName `
    -ProjectId $projectId

# ------------------------------------------------------------
# Apply Service Connection
# ------------------------------------------------------------

$applyResult = Configure-ServiceConnection `
    -ManagedIdentityName $ApplyManagedIdentityName `
    -ServiceConnectionName $ApplyServiceConnectionName `
    -FederatedCredentialName $ApplyFederatedCredentialName `
    -TenantId $tenantId `
    -SubscriptionId $ManagementSubscriptionId `
    -SubscriptionName $subscriptionName `
    -ProjectId $projectId

# ------------------------------------------------------------
# Summary
# ------------------------------------------------------------

Write-Host ""
Write-Host "============================================================"
Write-Host "Application Service Connections created/configured"
Write-Host "============================================================"

$planResult
$applyResult |
    Format-Table `
        ServiceConnectionName,
        ManagedIdentityName,
        ClientId `
        -AutoSize

Write-Host ""
Write-Host "Next:"
Write-Host "1. Verify both Service Connections in Azure DevOps."
Write-Host "2. Test them with AzureCLI@2."
Write-Host "3. Change the Application pipelines to use them."
Write-Host ""